// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "BlinkBreak",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "BlinkBreak",
            targets: ["AppModule"],
            bundleIdentifier: "com.praneel.BlinkBreak",
            teamIdentifier: "AD3WWZ7HNH",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.pink),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "Required to track eye movements for gameplay")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule"
        )
    ],
    swiftLanguageVersions: [.version("6")]
)